# -*- encoding=utf8 -*-
"""
author: panpan.du
date  : 2021.03.02
description: 用于记录程序中使用的常量信息
"""
"""==========================用户配置================================"""
# 用例表格路径
INPUT_EXCEL_PATH = "E:/生成用例/Utils-du/scripts_auto_create/case_excel/基础IO-Raid10-basic.xlsx"
# 用例sheet页名称
INPUT_EXCEL_SHEET_NAME = "基础IO-Raid10"
INPUT_FILE = "E:/生成用例/Utils-du\scripts_auto_create\conf_manager/basicio_raid10.txt"
CASE_SCRIPT_PART_PATH_NAME = "基础IO-Raid10.xlsx"

"""===========================用例表列项============================="""
case_number = "测试编号"
case_script = "脚本名称"
case_title = "用例标题"
case_product = "所属产品"
case_module = "所属模块"
case_object = "需求点"
case_type = "用例类型"
case_classification = "分类"
case_check_point = "检查项/测试点"
case_card = "卡类别"
case_physical_env = "物理环境"
case_pre_condition = "前提条件"
case_scene = "测试场景"
case_steps = "测试步骤"
case_expect = "预期结果"
case_priority = "优先级"
case_is_smoke = "冒烟测试"
case_is_mini = "最小用例集"
case_is_auto = "测试平台实现自动化"
case_time = "时间(min)"
case_author = "作者"
case_notes = "备注"
case_is_debug = "已调试"
case_result = "测试结果"
case_is_upload = "是否上传"

FRAMEWORK_EXCEL_CASE_ID = "caseId"
FRAMEWORK_EXCEL_CASE_TITLE = "caseTitle"
FRAMEWORK_EXCEL_CASE_VERSION = "caseVersion"
FRAMEWORK_EXCEL_CASE_TYPE = "caseType"
FRAMEWORK_EXCEL_CASE_LEVEL = "caseLevel"
FRAMEWORK_EXCEL_CASE_LOCATION = "scriptLocation"
FRAMEWORK_EXCEL_CASE_BRANCH_ID = "branchId"
FRAMEWORK_EXCEL_CASE_MODULE_ID = "moduleId"
FRAMEWORK_EXCEL_CASE_MODULE_NAME = "moduleName"
FRAMEWORK_EXCEL_CASE_STEP = "caseStep"
FRAMEWORK_EXCEL_CASE_RUN_ID = "runId"
FRAMEWORK_EXCEL_CASE_NEED_RUN = "needRun"

