# -*- encoding=utf8 -*-
"""
author: panpan.du
date  : 2021.01.18
description: 用于记录程序中使用的常量信息
"""

"""==========================表格名称用户相关================================="""
OUTPUT_EXCEL_FILE_NAME = "物理盘混组-Raid50"
OUTPUT_EXCEL_SHEET_NAME = "Raid50"
CASE_CONF_PATH = "test_conf/basic_io/raid50_mix.xml"


"""===========================用例默认参数脚本路径==============================="""
CASE_COMMON_DIR = "system_test/basic_io/raid_card/raid5"
CASE_MODULE_INDEX = 14
CASE_PRODUCT = "ROC_IOC (#19)"
CASE_MODULE = "/测试性要求/基础IO测试需求/数据通路/Raid5/Raid50/复杂场景(#1686)"
CASE_OBJECT = "无需求 (#0)"
CASE_TYPE = "系统测试-压力"
CASE_CARD = "RAID"
CASE_PHYSICAL_ENV = "物理环境_1"
CASE_PRIORITY = "A1"
CASE_IS_SMOKE = "N"
CASE_IS_MINI = "N"
CASE_IS_AUTO = "SYPN"
CASE_AUTHOR = "dupp"
CASE_DEBUG = "否"
CASE_IS_UPLOAD = "否"
CASE_TITLE_PREFIX = "基础IO-复杂场景"
CASE_NUMBER_PREFIX = "ps3_v1.1.0_basic_io_f"

"""===========================用例表列项============================="""
case_number = "测试编号"
case_script = "脚本名称"
case_title = "用例标题"
case_product = "所属产品"
case_module = "所属模块"
case_object = "需求点"
case_type = "用例类型"
case_classification = "分类"
case_check_point = "检查项/测试点"
case_card = "卡类别"
case_physical_env = "物理环境"
case_pre_condition = "前提条件"
case_scene = "测试场景"
case_steps = "测试步骤"
case_expect = "预期结果"
case_priority = "优先级"
case_is_smoke = "冒烟测试"
case_is_mini = "最小用例集"
case_is_auto = "测试平台实现自动化"
case_time = "时间(min)"
case_author = "作者"
case_notes = "备注"
case_is_debug = "已调试"
case_result = "测试结果"
case_is_upload = "是否上传"

"""===========================文件相关常量============================="""
OUTPUT_PRODUCT = "product"
EXCEL_COL_WIDTH = 15
DIR_CONNECTOR = "/"
CASE_NUMBER_CONNECTOR = "-"
CASE_SCRIPTS_PATH_CONNECTOR = "_"
CASE_TITLE_CONNECTOR = "-"
PYTHON_FILE_SUFFIX = ".py"
EXCEL_FILE_SUFFIX = ".xlsx"

"""===========================配置文件相关常量========================="""
ALL_INTERFACE_MEDIUM_CH = "所有介质接口"
ALL_INTERFACE_MEDIUM = "all_interface_medium"
ANY_INTERFACE_MEDIUM_CH = "任意一种物理盘"
ANY_INTERFACE_MEDIUM = "any_interface_medium"

POLLING_INTERFACE_MEDIUM_CH = "轮询介质接口"
JBOD = "JBOD"
RAID = "raid"


RAND_READ_MIO_CH = "混合大小IO随机读"
RAND_READ_MIO = "rand_read_mio"
SEQUENTIAL_READ_MIO_CH = "混合大小IO顺序读"
SEQUENTIAL_READ_MIO = "sequential_read_mio"
RAND_WRITE_MIO_CH = "混合大小IO随机写"
RAND_WRITE_MIO = "rand_write_mio"
SEQUENTIAL_WRITE_MIO_CH = "混合大小IO顺序写"
SEQUENTIAL_WRITE_MIO = "sequential_write_mio"
RAND_READ_WRITE_MIO_CH = "混合大小IO随机混合读写"
RAND_READ_WRITE_MIO = "rand_read_write_mio"
SEQUENTIAL_READ_WRITE_MIO_CH = "混合大小IO顺序混合读写"
SEQUENTIAL_READ_WRITE = "sequential_read_write_mio"
RAND_READ_SIO_CH = "小IO随机读"
RAND_READ_SIO = "rand_read_sio"
RAND_WRITE_SIO_CH = "小IO随机写"
RAND_WRITE_SIO = "rand_write_sio"
SEQUENTIAL_WRITE_LIO_CH = "大IO顺序写"
SEQUENTIAL_WRITE_LIO = "sequential_write_lio"


IO_PATTERN = "io_pattern_parm"
IO_PATTERN_CASE_SCRIPT = "case_script"
IO_PATTERN_CASE_TITLE = "case_title"
IO_PATTERN_IO_PRAM = "case_io_parm"
IO_PATTERN_IO_CHECK = "case_check_io"


CASE_CLASSIFICATION = "case_classification"
CASE_CLASSIFICATION_INDEX = "case_classification_index"
CASE_CLASSIFICATION_TAG = "case_classification_tag"
CASE_CLASSIFICATION_SCRIPT_DIR = "case_classification_script_dir"
CASE_CLASSIFICATION_VALUE = "case_classification_value"
CASE_CHECK_POINT = "case_check_point"
CASE_CHECK_POINT_INDEX = "case_check_point_index"
CASE_CHECK_POINT_VALUE = "case_check_point_value"
CASE_CHECK_POINT_TITLE = "case_check_point_title"
CASE_CHECK_POINT_SCRIPT_DIR = "case_check_point_script_dir"
CASE_SCENE = "case_scene"
CASE_SCENE_CONTEXT = "case_scene_context"
CASE_SCENE_RAID_PARM = "raid_parm"
CASE_SCENE_RAID_LEVEL = "raid_level"
CASE_SCENE_PD_COUNT = "pd_info"
CASE_SCENE_PD_PER_ARRAY = "pd_per_array"
CASE_SCENE_INTERFACE_MEDIUM = "interface_medium"
CASE_PRE_CONDITION = "case_pre_condition"
CASE_STEPS = "case_steps"
CASE_EXPECT = "case_expect"

"""===================================其他常量====================================="""
NONE_STR = "None"
TRUE_STR_LIST = ["yes", "YES", "Yes", "True", "TRUE", "true", True]
FALSE_STR_LIST = ["no", "NO", "No", "False", "FALSE", "false", False]
RAID_SCENE_CONNECTOR = "-"
RAID_ALL = "all"
